In [72]:
from bs4 import BeautifulSoup
import urllib.request
from datetime import datetime
import pandas as pd

In [51]:
def is_number(s):
    """ Returns True is string is a number. """
    return s.replace('.','',1).isdigit()

In [62]:
source = BeautifulSoup(open("./data/download/AAA.html"), "html.parser")

In [23]:
print(source)

<li class="header box_lsg_header">
<div class="row-time noline">Ngày</div>
<div class="row2">Thay đổi (+-/%)</div>
<div class="row1">Giá mở cửa</div>
<div class="row1">Giá cao nhất</div>
<div class="row1">Giá thấp nhất</div>
<div class="row1">Giá đóng cửa</div>
<div class="row1">Giá bình quân</div>
<div class="row1">Giá đóng cửa điều chỉnh</div>
<div class="row3">KL khớp lệnh</div>
<div class="row3">KL thỏa thuận</div>
</li>
<li>
<div class="row-time noline">
								    2019-08-27

								</div>
<div class="row2">
<span class="textdow">
                                                     -0.25
                                                     0.015151515151515152
                                                     <label class="print right icon-dow" id="hoseIcon"></label>
</span>
</div>
<div class="row1">16.55</div>
<div class="row1">16.65</div>
<div class="row1">16.2</div>
<div class="row1">16.25</div>
<div class="row1">
								   16.38
								</div>
<div class="row1">16.25</div>
<div class="row3">
								   2401690.0
								</div>
<div class="row3">


								           -



						        </div>
</li>
<li>
<div class="row-time noline">
								    2019-08-26

								</div>
<div class="row2">
<span class="textdow">
                                                     -0.4499999999999993
                                                     0.02654867256637164
                                                     <label class="print right icon-dow" id="hoseIcon"></label>
</span>
</div>
<div class="row1">16.85</div>
<div class="row1">16.9</div>
<div class="row1">16.3</div>
<div class="row1">16.5</div>
<div class="row1">
								   16.58
								</div>
<div class="row1">16.5</div>
<div class="row3">
								   2466420.0
								</div>
<div class="row3">


								           -



						        </div>
</li>
<li>
<div class="row-time noline">
								    2019-08-23

								</div>
<div class="row2">
<span class="textup">
									              0.05000000000000071
									              0.002958579881656847
									              <label class="print right icon-up" id="hoseIcon"></label>
</span>
</div>
<div class="row1">16.9</div>
<div class="row1">17.05</div>
<div class="row1">16.8</div>
<div class="row1">16.95</div>
<div class="row1">
								   16.92
								</div>
<div class="row1">16.95</div>
<div class="row3">
								   904360.0
								</div>
<div class="row3">


								           -



						        </div>
</li>
<li>
<div class="row-time noline">
								    2019-08-22

								</div>
<div class="row2">
<span class="texttrunglap">
                                                     0.0
                                                     0.0
                                                     <label class="print right icon-nochange" id="hoseIcon"></label>
</span>
</div>
<div class="row1">16.95</div>
<div class="row1">17.1</div>
<div class="row1">16.9</div>
<div class="row1">16.9</div>
<div class="row1">
								   16.99
								</div>
<div class="row1">16.9</div>
<div class="row3">
								   1181170.0
								</div>
<div class="row3">


								           -



						        </div>
</li>
<li>
<div class="row-time noline">
								    2019-08-21

								</div>
<div class="row2">
<span class="textup">
									              0.04999999999999716
									              0.002967359050444935
									              <label class="print right icon-up" id="hoseIcon"></label>
</span>
</div>
<div class="row1">16.85</div>
<div class="row1">17.05</div>
<div class="row1">16.7</div>
<div class="row1">16.9</div>
<div class="row1">
								   16.91
								</div>
<div class="row1">16.9</div>
<div class="row3">
								   2408380.0
								</div>
<div class="row3">


								           -



						        </div>
</li>
<li>
<div class="row-time noline">
								    2019-08-20

								</div>
<div class="row2">
<span class="textdow">
                                                     -0.09999999999999787
                                                     0.005899705014749137
                                                     <label class="print right icon-dow" id="hoseIcon"></label>
</span>
</div>
<div class="row1">16.95</div>
<div class="row1">17.15</div>
<div class="row1">16.85</div>
<div class="row1">16.85</div>
<div class="row1">
								   16.95
								</div>
<div class="row1">16.85</div>
<div class="row3">
								   1504480.0
								</div>
<div class="row3">


								           -



						        </div>
</li>
<li>
<div class="row-time noline">
								    2019-08-19

								</div>
<div class="row2">
<span class="texttrunglap">
                                                     0.0
                                                     0.0
                                                     <label class="print right icon-nochange" id="hoseIcon"></label>
</span>
</div>
<div class="row1">17.05</div>
<div class="row1">17.3</div>
<div class="row1">16.95</div>
<div class="row1">16.95</div>
<div class="row1">
								   17.08
								</div>
<div class="row1">16.95</div>
<div class="row3">
								   977320.0
								</div>
<div class="row3">


								           -



						        </div>
</li>

In [66]:
days = [datetime.strptime(x.get_text().strip(), "%Y-%m-%d")  for x in source.select("li div.row-time.noline")[1:]]
days

[datetime.datetime(2019, 8, 27, 0, 0),
 datetime.datetime(2019, 8, 26, 0, 0),
 datetime.datetime(2019, 8, 23, 0, 0),
 datetime.datetime(2019, 8, 22, 0, 0),
 datetime.datetime(2019, 8, 21, 0, 0),
 datetime.datetime(2019, 8, 20, 0, 0),
 datetime.datetime(2019, 8, 19, 0, 0)]

In [74]:
data_dict = {}
data_dict["date"] = days

In [68]:
prices = [(float(x.get_text().strip()) if is_number(x.get_text().strip()) else x.get_text().strip()) for x in source.select("li div.row1")]
prices

['Giá mở cửa',
 'Giá cao nhất',
 'Giá thấp nhất',
 'Giá đóng cửa',
 'Giá bình quân',
 'Giá đóng cửa điều chỉnh',
 16.55,
 16.65,
 16.2,
 16.25,
 16.38,
 16.25,
 16.85,
 16.9,
 16.3,
 16.5,
 16.58,
 16.5,
 16.9,
 17.05,
 16.8,
 16.95,
 16.92,
 16.95,
 16.95,
 17.1,
 16.9,
 16.9,
 16.99,
 16.9,
 16.85,
 17.05,
 16.7,
 16.9,
 16.91,
 16.9,
 16.95,
 17.15,
 16.85,
 16.85,
 16.95,
 16.85,
 17.05,
 17.3,
 16.95,
 16.95,
 17.08,
 16.95]

In [69]:
open_prices_dict = {"open": prices[6::6]}
highest_prices_dict = {"highest": prices[7::6]}
lowest_prices_dict = {"lowest": prices[8::6]}
close_prices_dict = {"close": prices[9::6]}
average_prices_dict = {"average": prices[10::6]}
adjusted_prices_dict = {"adjusted": prices[11::6]}

In [75]:
data_dict["open"] = prices[6::6]
data_dict["highest"] = prices[7::6]
data_dict["lowest"] = prices[8::6]
data_dict["close"] = prices[9::6]
data_dict["average"] = prices[10::6]
data_dict["adjusted"] = prices[11::6]

In [81]:
volumes = [((float(x.get_text().strip())) if is_number(x.get_text().strip()) else None) for x in source.select("li div.row3")[2:]]
volumes

[2401690.0,
 None,
 2466420.0,
 None,
 904360.0,
 None,
 1181170.0,
 None,
 2408380.0,
 None,
 1504480.0,
 None,
 977320.0,
 None]

In [71]:
trading_volumes_dict = {"trading_volume": volumes[0::2]}
put_through_volumes_dict = {"put_through_volume": volumes[1::2]}

In [76]:
data_dict["trading_volume"] = volumes[0::2]
data_dict["put_through_volume"] = volumes[1::2]

In [77]:
df = pd.DataFrame(data_dict)
df.head(10)

,date,open,highest,lowest,close,average,adjusted,trading_volume,put_through_volume
0,2019-08-27,16.55,16.65,16.20,16.25,16.38,16.25,2401690.0,None
1,2019-08-26,16.85,16.90,16.30,16.50,16.58,16.50,2466420.0,None
2,2019-08-23,16.90,17.05,16.80,16.95,16.92,16.95,904360.0,None
3,2019-08-22,16.95,17.10,16.90,16.90,16.99,16.90,1181170.0,None
4,2019-08-21,16.85,17.05,16.70,16.90,16.91,16.90,2408380.0,None
5,2019-08-20,16.95,17.15,16.85,16.85,16.95,16.85,1504480.0,None
6,2019-08-19,17.05,17.30,16.95,16.95,17.08,16.95,977320.0,None